export const MenuIconList = [
    {icon: 'finder'},
    {icon: 'spotify'},
    {icon: 'discord'},
    {icon: 'kindle'},
    {icon: 'whatsapp'},
    {icon: 'mail'},
    {icon: 'vscode'},
    {icon: 'photos'},
    {icon: 'netflix'},
    {icon: 'photoshop'},
    {icon: 'safari'},
    {icon: 'folder'},
    {icon: 'telegram'},
    {icon: 'vlc'},
]